[package]
name = "gist"
version = "1.0.1"
authors = ["Ben Wilber <benwilber@gmail.com>"]

[dependencies]
clap = "2.24.2"
exitcode = "1.0.1"
reqwest = "0.6.1"
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0.2"
